export const MienVietNam = ['xsmb', 'xsmt', 'xsmn'];
export const TinhThanh = [
  'Hồ Chí Minh',
  'Hà Nội',
  'Hải Phòng',
  'Cần Thơ',
  'Đồng Nai',
  'Thừa Thiên-Huế',
  'Bắc Ninh',
  'Hải Dương',
  'Nghệ An',
  'Thanh Hóa',
  'Nam Định',
  'An Giang',
  'Phú Thọ',
  'Tiền Giang',
  'Thái Bình',
  'Đồng Tháp',
  'Bắc Giang',
  'Vĩnh Long',
  'Lạng Sơn',
  'Ninh Bình',
  'Vĩnh Phúc',
  'Quảng Nam',
  'Bình Dương',
  'Đà Nẵng',
];
